/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.rizkiashari.restoapp.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.Text;
import com.huawei.agconnect.cloud.database.annotations.DefaultValue;
import com.huawei.agconnect.cloud.database.annotations.EntireEncrypted;
import com.huawei.agconnect.cloud.database.annotations.NotNull;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType JenisMakanan.
 *
 * @since 2022-01-22
 */
@PrimaryKeys({"id"})
@Indexes({"namaMakanan:namaMakanan"})
public final class JenisMakanan extends CloudDBZoneObject {
    private Integer id;

    private Integer idResto;

    private String namaMakanan;

    public JenisMakanan() {
        super(JenisMakanan.class);
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setIdResto(Integer idResto) {
        this.idResto = idResto;
    }

    public Integer getIdResto() {
        return idResto;
    }

    public void setNamaMakanan(String namaMakanan) {
        this.namaMakanan = namaMakanan;
    }

    public String getNamaMakanan() {
        return namaMakanan;
    }

}
