/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2019-2020. All rights reserved.
 * Generated by the CloudDB ObjectType compiler.  DO NOT EDIT!
 */
package com.rizkiashari.restoapp.model;

import com.huawei.agconnect.cloud.database.CloudDBZoneObject;
import com.huawei.agconnect.cloud.database.annotations.Indexes;
import com.huawei.agconnect.cloud.database.annotations.PrimaryKeys;

import java.util.Date;

/**
 * Definition of ObjectType RestoInfo.
 *
 * @since 2022-01-22
 */
@PrimaryKeys({"id"})
@Indexes({"namaResto:namaResto"})
public final class RestoInfo extends CloudDBZoneObject {
    private Integer id;

    private String image;

    private String namaResto;

    private String locationResto;

    private Date openDate;

    public RestoInfo() {
        super(RestoInfo.class);
    }

    public RestoInfo(Class<? extends CloudDBZoneObject> clazz, Integer id, String image, String namaResto, String locationResto, Date openDate) {
        super(clazz);
        this.id = id;
        this.image = image;
        this.namaResto = namaResto;
        this.locationResto = locationResto;
        this.openDate = openDate;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getImage() {
        return image;
    }

    public void setNamaResto(String namaResto) {
        this.namaResto = namaResto;
    }

    public String getNamaResto() {
        return namaResto;
    }

    public void setLocationResto(String locationResto) {
        this.locationResto = locationResto;
    }

    public String getLocationResto() {
        return locationResto;
    }

    public void setOpenDate(Date openDate) {
        this.openDate = openDate;
    }

    public Date getOpenDate() {
        return openDate;
    }

}
